---
# tasks file 
- name: Install curl unzip
  package:
    name: ['curl', 'unzip']
    state: present

- name: Download curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
- name: Unzip awscliv2.zip from previous step
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes
- name: Run the install script
  command: "/tmp/aws/install"
- name: Check the aws version
  command: "aws --version"
  